meta_product_name: "Senior"
meta_title: "Senior : Stay independant"
meta_description: "With this app, all senior can stay independant and organize life to stay at home !"
meta_image: "mamie-papy-box.png" # should exist in `app/assets/images/`
